### ISSUE TITLE
Playground Pack and HDRCore

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#1]
BitDepth() function are in both Playground Pack and HDRCore https://www.videoartifact.com/hdr/ or https://forum.doom9.org/attachment.php?attachmentid=16919&d=1564899530

so I think it's easy to change the Playground Pack one to something else

**Comment by Dogway** [comment]
º

**Comment by Dogway** [comment]
Thanks for the report, renamed to Dither_Bitdepth()
