### ISSUE TITLE
QTGMC is based on outdated version

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#10]
I did many updates based on your v3.33d, it's now in wiki too http://avisynth.nl/index.php/QTGMC

**Comment by Dogway** [comment]
Thank you! It's on my todo list. But after I finish TransformsPack and Stabilization Tools Pack. In any case QTGMC won't benefit much from HBD nor ExTools until 8-bit LUT processing is added to AVS+.

**Comment by realfinder** [comment]
I did your last update (Refinemotion) to QTGMC https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/QTGMC.avsi

**Comment by Dogway** [comment]
I did some formatting and cleanup (and a few small optimizations). You might want to check it out before I add further edits.
https://pastebin.com/qXjdBDB1

**Comment by realfinder** [comment]
I did quick compare and seems fine

**Comment by Dogway** [comment]
Thanks. Finally updated QTGMC, about same speed for 8-bits (until Expr includes 8-bit LUT support), 15% to 20% more speed for HBD.
