### ISSUE TITLE
ExTools v1.8 error SMDegrain

### ISSUE THREAD

**Issue by SangenBR** [Dogway/Avisynth-Scripts#12]
ExTools v1.8 error SMDegrain

was using this configuration

SMDegrain(tr=2,prefilter=0,pel=1,contrasharp=false,refinemotion=true,truemotion=false,chroma=true,plane=0,Str=1.8)

![Captura de tela 2021-06-17 220756](https://user-images.githubusercontent.com/42396360/122490580-b571d380-cfb8-11eb-832a-f4501f942a42.png)

**Comment by kedaitinh12** [comment]
Dogway was explained here
https://forum.doom9.org/showthread.php?p=1945218#post1945218

**Comment by SangenBR** [comment]
> Dogway was explained here
> https://forum.doom9.org/showthread.php?p=1945218#post1945218
Oh, Thx, I really hadn't read it on doom9.

**Comment by kedaitinh12** [comment]
New ver SMDegrain, try with last extools
https://github.com/Dogway/Avisynth-Scripts/blob/master/SMDegrain%20v.3.2.1d/SMDegrain%20v3.2.1d.avsi

**Comment by Dogway** [comment]
Rebased for the time being, so close.
