### ISSUE TITLE
Blur(.6)

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#13]
I seen documents only blur(1) = removegrain(12) but here is blur(.6) from original ver. Why you replaced blur(.6) with RemoveGrain (12)???
https://github.com/Dogway/Avisynth-Scripts/blob/ccabc3d261a787e38f762b4976cc3e698f226880/EX%20mods/FrameRateConverter.avsi#L246

**Comment by Dogway** [comment]
Because there was no fast HBD alternative to blur(.6), the closest was removegrain(12).
I can add some kernel that better matches blur(0.6) but it's not going to be as fast as removegrain though.

**Comment by Dogway** [comment]
Committed

**Comment by kedaitinh12** [comment]
Thanks
