### ISSUE TITLE
Why don't support y parameter in extools??

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#14]
I seen your ex_ farmily only support UV parameter and don't useable for y parameter??

**Comment by Dogway** [comment]
I add arguments as I need them in scripts so the lut family includes it. I didn't find a situation where it's required for the other functions so far. Do you have an example where it's needed?

**Comment by kedaitinh12** [comment]
I want use your extools to replace masktools2 functions in other scripts not your. But in other scripts have Y argument and i can't replace cause in extools don't have. Example: F3kgrain
http://avisynth.nl/index.php/F3kgrain

**Comment by Dogway** [comment]
So for makediff and adddiff. Added in: #2ef63fbb4fa97c8657a3a61461c03d0467133e3d

Untested.

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
but ex_merge still don't have Y agrument, in f3kgrain need it

**Comment by Dogway** [comment]
ex_merge is a bit of a disaster, currently my worst ported function mainly for the mask handling. It needs a refactor. I will reopen the issue and try to fix it as soon as possible taking a break from TransformsPack.

**Comment by kedaitinh12** [comment]
Thanks for your hardwork

**Comment by Dogway** [comment]
Committed: b9bbc6cc200456402c85759079dacd58cb45a2cd
Still not fast enough though due to BilinearResize and CombinePlanes... check benchmark list.

**Comment by kedaitinh12** [comment]
Thanks
