### ISSUE TITLE
ContraSharpeningHD may has issues

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#15]
see https://forum.doom9.org/showthread.php?t=175673

also I change things in my side https://github.com/realfinder/AVS-Stuff/commit/15ec37a05e090c9438fc855b7d2df572436ccb75

**Comment by Dogway** [comment]
Thank you. I will have a look and try to implement it for the next SMDegrain version, and later as part of the Sharpeners Pack when I have some break from Transforms Pack.

**Comment by Dogway** [comment]
Fixed: 1c3ef4f642d71ce9f957192e2a9e9d32e9874a3c
