### ISSUE TITLE
GradePack.v2.3

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#16]
I meet error with this enter space, you need delete it
https://github.com/Dogway/Avisynth-Scripts/blob/03d83eef09aa3e3ec5b8c7f017116c75452d60d1/GradePack.v2.3.avsi#L282

**Comment by Dogway** [comment]
Thanks, fixed: https://github.com/Dogway/Avisynth-Scripts/commit/906006c32c8ad74ee8d3c2e60ba25be7b9d8e4d9
I still had to optimize xer modes. Now ex_blend() is finished.

**Comment by kedaitinh12** [comment]
Thanks
