### ISSUE TITLE
QTGMC and vinverse

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#18]
seems there are issue https://github.com/Dogway/Avisynth-Scripts/blob/30600c68259c48a010595dff35067c83d6f44cbe/MIX%20mods/QTGMC.avsi#L1077 the plugin (dll) don't have custem parameter IIRC since I made it here http://forum.doom9.net/showthread.php?p=1921844#post1921844

**Comment by Dogway** [comment]
Thanks for the report, I will check it in the afternoon. There's still work to do as I plan to remove lsb and yuy2 (we have YV16 now) and do some visual benchmarks. Vinverse is much faster than the script so I will try to keep it.

**Comment by Dogway** [comment]
Fixed
