### ISSUE TITLE
Add BM3D to SMDegrain

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#19]
I think need add BM3D same KNLMeansCL prefilters for quality denoise

**Comment by Dogway** [comment]
Yes, it's on my todo list, thanks.

**Comment by Dogway** [comment]
Fixed: 1c3ef4f642d71ce9f957192e2a9e9d32e9874a3c

**Comment by kedaitinh12** [comment]
Thanks
