### ISSUE TITLE
Precise in QTGMC

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#20]
why Precise parameter removed? https://github.com/Dogway/Avisynth-Scripts/commit/a250d67083486881d57d799e4b29448bd60ed693#diff-8d412de5206b96cabe09eceee80daa532335a220fe60b611bc937d9fc5d2067d

QTGMC no longer work now, the last one here https://github.com/Dogway/Avisynth-Scripts/blob/b155ab6b5ead520c7dd868a5c873a7ac51019155/MIX%20mods/QTGMC.avsi work

**Comment by Dogway** [comment]
Thank you! I will have a look tomorrow, was busy with real life today.

**Comment by Dogway** [comment]
Fixed. 9868258fdde7a0f795fc26e46df0b700b00d9dd3
