### ISSUE TITLE
retinex_edgemask in FlatMask?

### ISSUE THREAD

**Issue by SangenBR** [Dogway/Avisynth-Scripts#28]
would be able to put retinex_edgemask in FlatMask?

https://github.com/Asd-g/AviSynth-Retinex
https://github.com/Asd-g/AviSynthPlus-Scripts/blob/master/retinex_edgemask.avsi

**Comment by Dogway** [comment]
Yes it's possible, flatmask is very outdated and there are some ideas to improve it but currently I'm a bit busy.

**Comment by SangenBR** [comment]
Ok, don't rush do it in your time
Thx

**Comment by Dogway** [comment]
I refactored FlatMask(), now it includes ex_retinex().
Check it here https://github.com/Dogway/Avisynth-Scripts/blob/e54132b704c280559b9557c51a8c7fe8e11fa9fc/MasksPack.avsi#L68 and let me know if it fits your needs.

**Comment by SangenBR** [comment]
> I refactored FlatMask(), now it includes ex_retinex(). Check it here:
> 
> https://github.com/Dogway/Avisynth-Scripts/blob/852790754e4ef7ae2cf0a5d520e8ce7b77da71d2/MasksPack.avsi#L68
> 
> and let me know if it fits your needs.

thx

**Comment by Dogway** [comment]
Closing for now.
Create a new issue if you have any problems.
