### ISSUE TITLE
SMDegrain & LSFmodex args

### ISSUE THREAD

**Issue by deadman0713** [Dogway/Avisynth-Scripts#31]
Updated to newest versions of your scripts today, finding a couple problems.
While in AVSPmod 3.7.0.
Updated Avisynth to test build 27 as well.

SMDegrain:
 Script error: smdegrain does not have a named argument "fulls" or "fulld"
_**edit: I see, you may have removed it as you did with QTGMC**_

SMDegrain 3.3.8d  with **contrasharp=55** fails in LSFmod call; while **contrasharp=true** works fine
Errors:
**Evaluate: operands of '/' must be numeric
LSFMod3.9_Mix line 631
SMDegrain3.3.8d line 482
SMDegrain3.3.8d line 593**

 In LSFmod 3.9:
     I commented this out at line 629 and replaced it with the line from the previous version
      rhlf  = ex_dlut("range_half", bi, fs)

I changed it to this, based on the previous version and it works, but I'm not sure if it's affecting something else off hand.
     rhlf  = Eval(ex_dlut("range_half", bi, fs))

Thank you for your continued work on these.

**Comment by Dogway** [comment]
Yes, I had some updates still pending for today. Got late while working on time for SoftLimiter().
Check with latest updates to see if it works now. Correct way is with Eval()

**Comment by deadman0713** [comment]
Updated the scripts, and everything seems to be working fine again.
Thanks!
