### ISSUE TITLE
SMDegrain v3.3.8d.avsi

### ISSUE THREAD

**Issue by HitmanJ** [Dogway/Avisynth-Scripts#32]
![imagem](https://user-images.githubusercontent.com/18430967/143604762-a8fab892-51f8-4446-898f-7b9974ddf06e.png)

**Comment by Dogway** [comment]
Hi. What's the SMDegrain() call?
Also AVS+ version.

**Comment by Dogway** [comment]
Closing for now. Open back if you get any issues.
