### ISSUE TITLE
LSharpAAF1.60.avsi typo

### ISSUE THREAD

**Issue by deadman0713** [Dogway/Avisynth-Scripts#34]
Lines 104 and 105 LSFMod calls should be **preset**="slow" instead of **default**="slow".

https://github.com/Dogway/Avisynth-Scripts/blob/e3156690a94dbf7e6a87d3f6b48dd4e396f0dda1/EX%20mods/LSharpAAF1.60.avsi#L104
https://github.com/Dogway/Avisynth-Scripts/blob/e3156690a94dbf7e6a87d3f6b48dd4e396f0dda1/EX%20mods/LSharpAAF1.60.avsi#L105

Thanks.

**Comment by Dogway** [comment]
Thanks. I have v1.70 ready since 2 months ago, time to give it a view and update. Should be in MIX mods though.

**Comment by deadman0713** [comment]
Excellent, thanks. Wasn't aware that LSharpAAF used FastLineDarken until I had a glance at it. 
Was looking for some AA utils and some alternative masking techniques to go along with FastLineDarken.

**Comment by Dogway** [comment]
Check here for the update:
https://github.com/Dogway/Avisynth-Scripts/blob/master/MIX%20mods/LSharpAAF1.70.avsi

Closing for now
