### ISSUE TITLE
function duplicates

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#4]
I seen some your plugin have same function name, i think you need rename it to don't meet any errors
"SmoothLevels" : "[PluginFunction]"
"SmoothLevels" : "C:\Program Files (x86)\AviSynth+\plugins+\GradePack.v1.1.avsi"
"SatMask" : "C:\Program Files (x86)\AviSynth+\plugins+\GradePack.v1.1.avsi"
"SatMask" : "C:\Program Files (x86)\AviSynth+\plugins+\Utils-r42.avsi"

**Comment by Dogway** [comment]
Thanks for the report.
SmoothLevels is a replacement for SmoothAdjust SmoothLevels, so you can remove the plugin. It was intentional unless someone has a reason to keep SmoothAdjust (?).
My SatMask (16-12-2011) precedes the one from Utils-r42, so I think they should change the name.

**Comment by kedaitinh12** [comment]
Cause smoothadjust don't only have smoothlevels function

**Comment by Dogway** [comment]
What do you use that doesn't have an alternative?

**Comment by realfinder** [comment]
I think it's better to pick another name in any case

Edit: for who those wondering, SatMask is ex_vibrance since 2021

**Comment by Dogway** [comment]
Ok, I'll think of a name

**Comment by kedaitinh12** [comment]
Thank realfinder and Dogway

**Comment by Dogway** [comment]
fixed
