### ISSUE TITLE
Error with fillmissing / FrameRateConverter

### ISSUE THREAD

**Issue by Kuronoe-Ookami** [Dogway/Avisynth-Scripts#40]
Hi,
I'm having an error testing your filter.

![SHOA015121](https://user-images.githubusercontent.com/72235923/147894401-1f427b0e-dc03-42de-9317-b1ee45581c9d.png)
![SHOA015121](https://user-images.githubusercontent.com/72235923/147894651-3d073a9c-96a8-4d3f-b6a8-70e287d486d2.png)

I don't know if it's a bug, but I'm reporting it.
I'm using the latest versions here from github.

Thanks for your work.

**Comment by Dogway** [comment]
Thanks for the report. Yes FrameRateConverter needs a quality check due to core issues and some inconsistencies issued [here](https://forum.doom9.org/showthread.php?p=1959872#post1959872).
Since I got no response I will do a best-guess and release a working version as soon as I can.

**Comment by Dogway** [comment]
Fixed 14ed34ce830581a2815d55c4f5141b49e8c9045c and 380d87b9e412a6d8155391a898d392d2d215094b

**Comment by Dogway** [comment]
Yes, some people get that error when calling propNumElements() outside a runtime environment. Either it's a bug in AviSynth+ 3.7.1 x86 or you are using an older AVS+ version.

**Comment by Kuronoe-Ookami** [comment]
Hi,
I'm using Avisynth+ version 3.7.0.3382.
I always keep it up to date.

I don't know what it could be : (

Thank you.

**Comment by Dogway** [comment]
Yes, that's why. Update to latest AVS+ 3.7.1, released 10 days ago.
https://github.com/AviSynth/AviSynthPlus/releases

**Comment by Kuronoe-Ookami** [comment]
![TEST000000](https://user-images.githubusercontent.com/72235923/148816040-d3281a5e-96ce-48bc-a2a5-28fafce8dd6b.png)

I updated, but now another error has appeared in ex_framerateconverter/fillmissing.
Thank you anyway.

**Comment by Dogway** [comment]
I don't understand why that is happening. I just tested FrameRateConverter and everything is fine.
That Assert is from ex_inpand():
https://github.com/Dogway/Avisynth-Scripts/blob/de2ce0d7b999631e13182ec7254df489fc387ba0/ExTools.avsi#L5846

which in turn calls ex_bs() and triggers and exception at "**ibi = ibi-ibi%2**":
https://github.com/Dogway/Avisynth-Scripts/blob/de2ce0d7b999631e13182ec7254df489fc387ba0/ExTools.avsi#L6804

Everything so far is in integers so I don't know. In any case you are using EX mod. Try to use MIX mod to see if it circumvents the issue, it's also a bit faster although it requires RgTools and MaskTools2 in addition.
