### ISSUE TITLE
ResizersPack.avsi line 360 error

### ISSUE THREAD

**Issue by deadman0713** [Dogway/Avisynth-Scripts#41]
Have an error in line 360:

https://github.com/Dogway/Avisynth-Scripts/blob/2600adb01bc5d27b9b4eee8d3cfb5561f02c1532/ResizersPack.avsi#L360

I just removed the extra close brackets, and it works again in AVSPmod... but not sure if it is doing what it is supposed to.
 Return "$"+string(Y,2)+string(U,2)+string(V,2) }

Can't test anymore tonight now.
Thanks.

**Comment by Dogway** [comment]
Fixed (I think): 7dfabfeeb28b7c7aabf9ca0f6ba1d8af2d32b13d
