### ISSUE TITLE
SMDegrain Lrad

### ISSUE THREAD

**Issue by deadman0713** [Dogway/Avisynth-Scripts#42]
A couple Lrad calls are still in  SMDegrain when LSFmod is used.
Just updated both new versions, and the error popped up. Lrad was as removed in LSFMod 4.2mix. I jumped from LSFmod 4.1 to 5.0, so missed that change.

Lines 506 and 507 in SMDegrain:

https://github.com/Dogway/Avisynth-Scripts/blob/36e27b554116f1ff0285eebd53d32c3a26fea23b/SMDegrain%20v3.4.3d/SMDegrain%20v3.4.3d.avsi#L506

Thanks.

**Comment by Dogway** [comment]
Yes thanks. I still have to rebase SMDegrain and TransformsPack. Will upload today or tomorrow.

**Comment by Dogway** [comment]
Fixed in af0c41b72aac29c669c6ea8a12c6a3dbb06946bb
