### ISSUE TITLE
Invalid arguments to function 'propDelete' when using ex_edge()

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#45]
A change between commit https://github.com/Dogway/Avisynth-Scripts/commit/361d4b3609e9da732248e3ec2cb059b308b9e383 and https://github.com/Dogway/Avisynth-Scripts/commit/f38f458f1c9a0da1c2bd3cc1606485ef6cba297b (latest) introduced a bug in extools.avsi in line 6618.
It can be triggered with a simple ex_edge() call, no args necessary, like so:

ColorBarsHD()
ex_edge()

```
[avisynth @ 0000020643109640] Script error: Invalid arguments to function 'propDelete'.
(C:/Program Files (x86)/AviSynth+/plugins64+/ExTools.avsi, line 6618)
(Z:\test.avs, line 3)
Z:\test.avs: Unknown error occurred
```

**Comment by Dogway** [comment]
It works for me, ex_edge() doesn't require TransformsPack. Are you using latest AVS+ v3.7.2 test version?

**Comment by Kogarou-san** [comment]
I wasn't, hadn't check for updates yet. Works after updating to Avisynth+ 3.7.2 test 12
Sorry, thank you for the support.
