### ISSUE TITLE
DeblockPack

### ISSUE THREAD

**Issue by TbtBI** [Dogway/Avisynth-Scripts#48]
Hi, `Deblock_QED(uv=2)` and `Deblock_QED(uv=3)` give identical chroma output.

`MCDeblockFFT3D(uv=2)` doesn't copy chroma planes.

**Comment by Dogway** [comment]
Strange, doesn't happen to me:
```
a=extractu()
Deblock_QED(quant1=30, quant2=40,UV=3)
extractu()

ex_makediff(a, metric="none", aug=true, dif=true, show=3)
```

As for MCDeblockFFT3D(uv=2) I fixed already, will upload in next version.

**Comment by TbtBI** [comment]
Sorry, Deblock_QED is ok for me too. I updated ExTools and restarted AvspMod.

Thanks for the MCDeblockFFT3D fix.
