### ISSUE TITLE
AVS+ version check

### ISSUE THREAD

**Issue by TbtBI** [Dogway/Avisynth-Scripts#49]
There is [this check](https://github.com/Dogway/Avisynth-Scripts/blob/master/EX%20mods/FastLineDarken%202.3%20MOD.avsi#L70) that is not ideal imo.

If I compile avs+ from the current state (master branch and the latest commit) I will have avs+ 3.7.1 r3660 ( https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/core/version.h.in#L9 ). The version will be changed (3.7.1->3.7.2) when official avs+ build is released.

**Comment by Dogway** [comment]
Ok, I wasn't aware of that.
AVS+ was updated to v3.7.2 a few hours ago, does that solve the issue?

**Comment by TbtBI** [comment]
Yes.
