### ISSUE TITLE
Stabilization Tools Pack 2.1 mod 2.52 by A.SONY in (18-09-2020)

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#5]
I think you mod from out date of ver by real.finder (18-09-2020). I seen real.finder updated to 29-11-2020. Why you don't base on 29-11-2020 and update it to new ver??
https://github.com/realfinder/AVS-Stuff/commits/Community/avs%202.5%20and%20up/StabilizationToolsPack.avsi

**Comment by kedaitinh12** [comment]
I seen your ver different real.finder and can put same autoload folder but still functions duplicate FilmGateFix(). If you won't deveploment FilmGateFix() in future, can you delete it??

**Comment by Dogway** [comment]
I saw real.finder's update. I revised it and didn't find much to update, so I just changed his ver in header.
I'm taking another route and Stab v4.0 saw a big overhaul including FillBorder().
FilmGateFix() will be revised in the medium future.

**Comment by kedaitinh12** [comment]
Ok, i will delete filmgatefix() in real.finder ver
