### ISSUE TITLE
vsTCanny update(s) broke ex_retinex()

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#50]
I just updated vsTCanny and it seems it broke ex_retinex()
More specifically, it's likely to come from https://github.com/Asd-g/AviSynth-vsTCanny/releases/tag/1.1.0 , but versions https://github.com/Asd-g/AviSynth-vsTCanny/releases/tag/1.1.6 and https://github.com/Asd-g/AviSynth-vsTCanny/releases/tag/1.1.7 also changed defaults for U and V, so it's likely those broke ex_retinex() too.

```
[avisynth @ 000001df36949680] vsTCanny: sigma_vY must be greater than or equal to 0.0.
(C:/Program Files (x86)/AviSynth+/plugins64+/ExTools.avsi, line 1792)
(C:/Program Files (x86)/AviSynth+/plugins64+/ExTools.avsi, line 1828)
(C:/Program Files (x86)/AviSynth+/plugins64+/SMDegrain v3.4.8d.avsi, line 875)
(test.avs, line 3)
test.avs: Unknown error occurred
```

Using latest commit https://github.com/Dogway/Avisynth-Scripts/commit/cb9af65d9711747369815b32f1c4091ef1bf296e with AVS+ 3.7.2

**Comment by Dogway** [comment]
That's right, I had ExTools pending of update, I think that fixes it.

**Comment by Kogarou-san** [comment]
I haven't used it before so I don't know if the output is correct, but it works now
Thanks
