### ISSUE TITLE
SMDegrain does not work when interlaced=true && pel!=1 in SD clips

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#51]
SMDegrain's interlaced flag does not work with interlaced SD video, unless you manually set pel to 1; 2 or 4 throw an error

Using an interlaced source should be more useful than creating a ColorBar clip; I found this sample to be enough https://forum.videohelp.com/attachments/56920-1611374890/20090227_233739-H.264.m2ts_1080i_interlaced_letterman_sample.mp4
```
LSMASHVideoSource("20090227_233739-H.264.m2ts_1080i_interlaced_letterman_sample.mp4") #or other interlaced videos
BicubicResize(720,480) #necessary for HD videos such as above
SMDegrain(interlaced=true)
```

```
[avisynth @ 0000012a200c9740] MSuper: pelclip frame size must be Pel of source!
(C:/Program Files (x86)/AviSynth+/plugins64+/SMDegrain v3.4.8d.avsi, line 279)
(C:/Program Files (x86)/AviSynth+/plugins64+/SMDegrain v3.4.8d.avsi, line 634)
(test.avs, line 3)
test.avs: Unknown error occurred
```
Also related:
On SMDegrain's script @ line 221:
```
    # Input preparation for: Interlacing, Motion Filter and MSuper optimization when pel=2

    inputP  = !isInter ? (pel == 2 ? input.AssumeFrameBased()           : input)                             : \
```
Correct me if I'm wrong, but shouldn't it be `pel>=2` instead? Or is it not related to what the mvtools2 docs state here?
> Note: MAnalyse (if pel ≥ 2) detects fieldbased video flag (after SeparateFields) and automatically makes correction of motion vectors according to verticlal shift of fields with different parity.

Using https://github.com/Dogway/Avisynth-Scripts/commit/cb9af65d9711747369815b32f1c4091ef1bf296e and AVS+ 3.7.2

**Comment by Dogway** [comment]
Thanks for the notes, yes pel ≥ 2 was added after I worked on interlacing support, a long time ago. Surely there are more interlacing related issues around (ie. 'show' is broken), but I will fix them slowly.
For the time being I fixed the pelclip bug. Will upload in a moment.

**Comment by Dogway** [comment]
Closing this. If you still run into issues, let me know here.
