### ISSUE TITLE
ChromaReconstructor_faster needs 'gpuid'

### ISSUE THREAD

**Issue by mysteryx93** [Dogway/Avisynth-Scripts#52]
For ChromaReconstructor_faster, and anywhere you use KNLMeansCL, it's important to expose the parameter `gpuid`. Sometimes it won't work on the default device, and on dual-graphics, the default will run on Intel instead of NVidia. Ideally, set `device_type="cpu"` if `gpuid==-1` (although CPU mode isn't currently working but should be fixed at some point?)

**Comment by Dogway** [comment]
Completed in:
1ea9388883189aa028945f5da40fda25dbafbd41
1ca7fdc7054874693c52dcde92f624085f843dfe

**Comment by Dogway** [comment]
Thanks, check now:
70d5fd151d439a702efc60e254277e5609a44688
33b8b05b0d88e87db78bda2a6dbff4693d3d0d2e
