### ISSUE TITLE
Delete zopti2 parameter

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#53]
If don't use this anymore why don't remove it??
https://github.com/Dogway/Avisynth-Scripts/blob/1ca7fdc7054874693c52dcde92f624085f843dfe/ResizersPack.avsi#L56

**Comment by Dogway** [comment]
Yes, forgot to update it!

**Comment by Dogway** [comment]
Commited: c113ff30e37f47d8117c1b3db8f00599cc62e267

**Comment by kedaitinh12** [comment]
Thanks
