### ISSUE TITLE
smdegrain does not have named argument lsb

### ISSUE THREAD

**Issue by madey83** [Dogway/Avisynth-Scripts#54]
when i use latest SMdegrain in StaxRip with this command:

SMDegrain(tr=2,thSAD=250,contrasharp=true,refinemotion=true,lsb=true)

i got this error: 

smdegrain does not have named argument lsb

Could  you please advice what to do to solve this issue?

**Comment by Dogway** [comment]
LSB is deprecated since native HBD support was added to AviSynth+ ( a few years back)
The current workflow would become:
```
ConvertBits(16)
SMDegrain(tr=2,thSAD=250,contrasharp=true,refinemotion=true,lsb=true)
ConvertBits(8,dither=1)
```
Read the script dependencies, but they shouldn't be many with this simple call.

**Comment by madey83** [comment]
thank you for replay.

when i pasted your code in StaxRip SMDegrain field i got error like: Script error: There is no function named 'ex_bs'. 
Video process in application is in 10bit.
This is all my filters use in StaxRip
![image](https://user-images.githubusercontent.com/34553588/172063478-fa8dff3d-7a73-4827-ac07-9dbd520153d3.png)

to be more precise what i would like to achieve is have more accurate denoise which was enabled by lsb (32bit) option in old version like example: version v3.1.2.110s :: http://avisynth.nl/index.php/SMDegrain
"lsb bool = False
This enables 32 bit depth precision for denoising. You gain extra denoising accuracy, most noticeable in the prevention of banding in flat areas. Automatically set if either lsb_in or lsb_out are enabled. .."

Could you please guide me hot to have this?

**Comment by Dogway** [comment]
Yes, ConvertBits(16) is the same if not better because it's native and performs faster.

SMDegrain as I said has a few dependencies. For a simple call like that you need:

- [ExTools](https://github.com/Dogway/Avisynth-Scripts/blob/master/ExTools.avsi)
- [SharpenersPack](https://github.com/Dogway/Avisynth-Scripts/blob/master/MIX%20mods/SharpenersPack.avsi)
- [ResizersPack](https://github.com/Dogway/Avisynth-Scripts/blob/master/ResizersPack.avsi)

**Comment by madey83** [comment]
hi Dogway,

thank you for your feedback.

when i use this code for SMDegrain:
import("E:\4k encode\Avisynth-Scripts-master\ExTools.avsi")
import("E:\4k encode\Avisynth-Scripts-master\MIX mods\SharpenersPack.avsi")
import("E:\4k encode\Avisynth-Scripts-master\ResizersPack.avsi")

ConvertBits(16)
SMDegrain(tr=1, thSAD=300, thSCD2=100, contrasharp=false, refinemotion=true, search=3)
ConvertBits(bits=10, dither=1)

and this for LSFmod:
import("E:\4k encode\Avisynth-Scripts-master\MIX mods\LSFplus.avsi")
LSFPlus(preset="slow",strength=200)

it work, but very slow, compare to my old settings.

Old settings give me ~10 fps
new settings give me ~4,2 fps

what did i do wrong to slow down that much?

**Comment by Dogway** [comment]
'Slow' is rather slow, reason being it uses supersampling.
If your source is HD I recommend you to use 'LSF' not only is faster but yields better quality for HD.

**Comment by madey83** [comment]
thank you.
