### ISSUE TITLE
Add nnedi3cl to the scripts

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#56]
Self-explanatory.
I'm still trying it out, since it's so recent, but Asd-g should be pretty quick at fixing bugs, once reported.
Thank you.

**Comment by Dogway** [comment]
Oh so great, wasn't aware he finally ported. Will test and implement for the next week.

**Comment by Dogway** [comment]
Done. Hopefully without any issues. Just keep in mind that nnedi3 and NNEDI3Cl don't output the same mathematical output.

**Comment by Kogarou-san** [comment]
Maybe adding a way to use CPU as an option or as a fallback might be useful, for those unwilling/unable to use oCL (unless nnedi3cl on the CPU is as fast as nnedi3, which I doubt)

**Comment by Dogway** [comment]
Yes QTGMC+ is updated already with NNEDI3CL but bottleneck is elsewhere so not much of an improvement.
Does NNEDI3CL have an option for CPU? I didn't see it...
Integrating both options at the same time is a pain, unless I make a wrapper for both.

**Comment by Kogarou-san** [comment]
The ability to offload some of the compute to a GPU is still beneficial since you can spend those now free CPU cycles elsewhere
> Does NNEDI3CL have an option for CPU? I didn't see it...
It does not, unless you'd set it to run the oCL kernel on the CPU, but that's slower and defeats the purpose
> Integrating both options at the same time is a pain, unless I make a wrapper for both.
A wrapper might come in handy, there isn't much difference in them besides no built-in rpow2 for CL, less prescreener options, and possibly different defaults, as far as I know

**Comment by Dogway** [comment]
Check here: 47b055858eed471b5cdc7ae85939ddb0d70f907b
Also in SMDegrain (not uploaded yet), still need to implement in QTGMCp()

**Comment by Kogarou-san** [comment]
I will take a look at it and play around tomorrow, thanks!
