### ISSUE TITLE
SMDegrain v3.5.3d performance / bitrate consumtion for encode

### ISSUE THREAD

**Issue by madey83** [Dogway/Avisynth-Scripts#57]
Encode with new SMDegrain v3.5.3d is slower and it needs more bitrate than old one:

import("E:\4k encode\Avisynth-Scripts-master\ExTools.avsi")
import("E:\4k encode\Avisynth-Scripts-master\ResizersPack.avsi")
Import("E:\4k encode\Avisynth-Scripts-master\SMDegrain v3.5.3d\SMDegrain v3.5.3d.avsi")
import("E:\4k encode\Avisynth-Scripts-master\TransformsPack - Main.avsi")
import("E:\4k encode\Avisynth-Scripts-master\TransformsPack - Models.avsi")
import("E:\4k encode\Avisynth-Scripts-master\TransformsPack - Transfers.avsi")
SetMemoryMax()
ConvertBits(16)
SMDegrain(tr=2, thSAD=500, thSCD2=100, contrasharp=false, refinemotion=true, truemotion=false, LFR=150, DCTflicker=true, subpixel=3, Chroma=true)
ConvertBits(10,dither=1)

gives 5,439 fps and 4026 kb/s bitrate for 2 minutes clip

old SMDegrain v3.1.2d settings:
SMDegrain(tr=2, thSAD=500, thSCD2=100, contrasharp=false, refinemotion=true, truemotion=false, lsb=false, subpixel=3, Chroma=true)

gives 7,290 fps and 3513 kb/s fot the same 2 minutes clip.

**Comment by Dogway** [comment]
Try with LFR=0 to disable it and compare apples to apples.

**Comment by madey83** [comment]
hi Dogway,

 with LFR=0  i got 5.900 fps and 3518 kb/s

**Comment by madey83** [comment]
hi Dogway,
with LFR=0  i got 7.440 fps and 2793 kb/s for 2 minutes clip.

so what exactly LFR does. I saw this option on forum, but without details about it.

**Comment by Dogway** [comment]
It's for recovering low frequency smearing, like when you lose some shading (walls, clouds...) when movement takes place.
It depends heavily on source grain and SMDegrain strength settings so you have to test if it works for you. It's slower specially when DCTFlicker=true.

**Comment by madey83** [comment]
thank you for the information.

in last relase on SMDegrain i noticed that you added "subpixel=4" but i did not see this option in attached to script folder dokumentation.

Could it be possible to update dokumentation for all new stuff you were added to SMDegrain plus some code examples how to use the option?

I would be grate !.

Many thanks for your work and quick answers.

**Comment by Dogway** [comment]
No prob. Will do around August/September.
