### ISSUE TITLE
Can't use ChromaReconstructor() with the default values

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#58]
**Describe the bug**
KNLMeansCL: 'channels' must be 'Y' with greyscale pixel format!
(`C:/Program Files (x86)/AviSynth+/plugins64+/ChromaReconstructor v3mod.avsi`, line 46)

**To Reproduce**
```cpp
ColorBarsHD()
ChromaReconstructor()
```

**Expected behavior**
Working

**Files**
Script pack commit https://github.com/Dogway/Avisynth-Scripts/commit/75ac682b5559a426d43d1ca7abda8574ffa0f341;  `KNLMeansCL v1.1.1e`

**System:**
 - Windows 10
 - `AviSynth+ 3.7.2 (r3679, master, x86_64)`,

**Comment by Dogway** [comment]
Thanks, fixed in: 113f14dc4d89f2b98710c076c56656683762d526

**Comment by Dogway** [comment]
Did it fix it?

**Comment by Kogarou-san** [comment]
I updated to https://github.com/Dogway/Avisynth-Scripts/commit/361f43ec56d0952f73a031f6c8922ba679004eff, now works when testing with `ColorBarsHD()` as source, but got a different error message in a bigger script:
```cpp
LWLibavVideoSource("path to remuxed Japanese NTSC DVD.mkv", threads=1, decoder="mpeg2_cuvid")
AssumeTFF()

QTGMCp(Preset="Slower", NNSize=0, NNeurons=4, EdiQual=2, TrueMotion=true, ChromaMotion=true, ThSAD1=500, ThSAD2=200, Blocksize=16, ForceTR=6, SubPel=4, NoiseProcess=0, ChromaNoise=false, Denoiser="", NoiseTR=0, Sigma=0, NoiseDeint="", StabilizeNoise=false, DenoiseMC=false, show=false, tv_range=true, device_type="GPU", device_id=0)
super=MSuper(pel=4, levels=1) 
MDegrain6(super, QTGMC_bVec1,QTGMC_fVec1, QTGMC_bVec2,QTGMC_fVec2, QTGMC_bVec3,QTGMC_fVec3, QTGMC_bVec4,QTGMC_fVec4, QTGMC_bVec5,QTGMC_fVec5, QTGMC_bVec6,QTGMC_fVec6, 500, 200, mt=false)  

ChromaReconstructor()
```

```
KNLMeansCL: 'rclip' does not match the source clip!
(C:/Program Files (x86)/AviSynth+/plugins64+/ChromaReconstructor v3mod.avsi, line 47)
```
[Screenshot of the clip and frameprops just before](https://kogarou.s-ul.eu/kpkAIz1c.png)

**Comment by Dogway** [comment]
ChromaReconstructor() as strange as it sounds requires 444 input (ie. `ConvertToYUV444(chromaresample="spline16")` )
I refactored ChromaReconstructor_faster() to make more sense and it accepts 420 inputs, also is considerably faster with practically the same output.

I updated the function to remove SysInfo references. 2567c3817e498ee5e45c9bc6e89f7492990bc8f9

**Comment by Kogarou-san** [comment]
> ChromaReconstructor() as strange as it sounds requires 444 input

Oh yeah I forgot about that, oops! I wonder if you could add a simple 420->444 conversion internally: IIRC the docs/comments (or used to?) say to simply use `ConvertToYUV444()` before using it, and since the whole point of the function is to unscrew chroma, I assume the way you upscale the chroma planes does not matter the slightest, quality-wise (correct me if I'm wrong tho)

And yeah, it took 6 minutes or so to do a single 1288x720 frame, have completely forgot about the _faster() one as well 😅

**Comment by Dogway** [comment]
Maybe the improvement is negligible since rclip from KNLMeansCL does warp the chroma edges so much, but I like to play it safe in any case, spline16 is a good neutral upscaler.

Maybe now with GPU nnedi3 _faster() version runs slightly faster, I don't know.
gpuid=-1 is also passed to KNLMeansCL, but it still doesn't support cpu mode(?), maybe report there?

Close if everything's fine.

**Comment by Kogarou-san** [comment]
There are Non-Local Means plugins made specifically for the CPU, but I don't know how well it runs.
Everything seems to be fine, haven't tested much but the original issue is fixed. Closing.
Thank you
