### ISSUE TITLE
QTGMC+ 3.88p

### ISSUE THREAD

**Issue by Blankmedia1** [Dogway/Avisynth-Scripts#65]
**Describe the bug**
Vinverse clip2's number of frames doesn't match.
line 1188 and 959

**To Reproduce**
QTGMCp(preset="Very Slow", InputType=1, TR2=5, Sharpness=0.5, Nnsize=3, NNeurons=3, EdiMode="BWDIF+NNEDI3")
I think it related to the edimode with BWDIF

**Expected behavior**
clip 2 number of frame should be the same

thanks again mate!

**Comment by Dogway** [comment]
commit 23515d5ca598503c789fca687f8032846a58ac4c
