### ISSUE TITLE
QTGMC+: Slow starup and encoding speed

### ISSUE THREAD

**Issue by marukuru** [Dogway/Avisynth-Scripts#67]
**Describe the bug**
Sometime the encoding (x264) takes several hours to start (x264 header is shown, but encoding doesn't start), and then runs really slow, like 0,01fps slow with `x264 --preset slow`

**To Reproduce**
```
SetMemoryMax(16000)
SetCacheMode(CACHE_OPTIMAL_SIZE)
SetFilterMTMode("DEFAULT_MT_MODE", MT_MULTI_INSTANCE)
LWLibavVideoSource("file.mkv", threads=16, prefer_hw=3, format="YUV422P10")
AssumeFPS("ntsc_video")
AssumeBFF()
QTGMCp(Preset="Slow", EdiMode="NNEDI3", Threads=20, Denoiser="fft3df", EZDenoise=1.0, NoisePreset="Slow", device_type="gpu", device_id=0)
Prefetch(20,20)
```

1. Encoding is slow
2. Kill process
3. Restart encoding, encoding runs at normal speed

**Expected behavior**
Encoding should run at normal speed

**System:**
 - Ubuntu 22.04
 - Intel compute runtime 22.41.24420
 - Latest version of scripts & plugins
 - AviSynth+ 3.7.2 (r3818, master, x86_64)
 - x264 0.164.3098M 7628a56 with AVS input
 - i9-10850K CPU @ 3.60GHz, 64GB RAM

**Comment by Dogway** [comment]
Seems to be a problem with this line:
`SetCacheMode(CACHE_OPTIMAL_SIZE)`
Without it it runs at about 5.3fps on my CPU (i7-4790K) in AVSMeter. Should run faster on your CPU.

In any case it's a bad idea to deinterlace and encode at the same step, you will get better absolute times encoding to lossless (or transparent) then to H264.

Another idea is to use DGSource, not sure if possible in Ubuntu. And probably to output to YUV420 from loader, 422 is a bit more taxing in QTGMC.

**Comment by marukuru** [comment]
Hi @Dogway, thanks for your comment. I'll remove `SetCacheMode` and give it some testing. I'll read before adding it, that it might slow down startup, but what put me off was, that this behavior wasn't deterministic. Out of three encoding attempts one would startup and encode at normal speed (some minutes startup time vs. several hours).

**Comment by Dogway** [comment]
Well deterministic or not it still seems it's a problem with `SetCacheMode(CACHE_OPTIMAL_SIZE)`.
It might be the case of a problem with non linear access to frames, like scripts that deal with temporal filters.

Maybe you can try with RequestLinear(32) before QTGMCp(). Also try to align memory assignment like SetMemoryMax(2048*8)

**Comment by Dogway** [comment]
Could you test the above?

**Comment by marukuru** [comment]
@Dogway Thanks, will give it a try this week. As for now I can confirm, that removing `SetCacheMode(CACHE_OPTIMAL_SIZE)` fixes both, the slow startup and encoding speed.

**Comment by Dogway** [comment]
Ok, closing for now. Reopen if needed.
