### ISSUE TITLE
Errormessage "nnedi3wrap does not have a named argument "dh"" when loading 

### ISSUE THREAD

**Issue by ChristianWaechter** [Dogway/Avisynth-Scripts#69]
**Describe the bug**
When I try to run the QTGMC+ script (v3.87+), I get the error message as shown in the title.

**To Reproduce**
Video file is a DV-video loaded with AVISource() and the Cedocida DV Codec. QTGMC+ call is like shown below.
`clip1 = QTGMCp(clip1, Preset="Placebo", SourceMatch=3, MatchPreset="placebo", MatchPreset2="Placebo", Sharpness=0.25, SLMode=4, SOvs=2, SVThin=0.5, TR2=1, Rep0=1, Rep1=0, Rep2=4, RepChroma=True, Lossless=2, EdiMode="NNEDI3", NNSize=3, NNeurons=4, EdiQual=2, EdiMaxD=3, NoiseProcess=2, ChromaNoise=true, Denoiser="dfttest", DenoiseMC=true, NoiseTR=2, Sigma=1.8, GrainRestore=0.4, NoiseRestore=0.2, NoiseDeint="Generate", StabilizeNoise=true, Precise=true, ShowNoise=0)`

**Expected behavior**
QTGMC+ works as QTGMC

**System:**
 - Windows 10
 - AVS+ v3.7.2 x64 20220317
 - ResizersPack 10.8
 - NNEDI3CL-1.0.5
 - All other Pluginfiles downloaded today
 - AMD Ryzen 5900X
 - 64 GB RAM
 - Radeon RX 6600 XT

**Additional context**
- It is actually true that there is no parameter "dh" the function definition in line 640 in the ResizersPack.avsi
`function nnedi3wrap(clip a, int "xfactor", int "yfactor", int "field", int "nsize", int "nns", int "qual", int "etype", int "pscrn", string "cshift", int "fwidth", int "fheight", float "src_left", float "src_top", int_array "planes", bool "HBD", float "sharpness", int "gpuid")`
- When I remove the parameter in the function call in file QTGMC+.avsi in line 1161, I get the error message below. But I do not see a newer AviSynth version nor can I get a older ResizerPack.avsi to test
>    nnedi3wrap: Update AviSynth+ version
> (AviSynth_Plugins/ResizersPack.avsi, line 677)
> (AviSynth_Plugins/QTGMC+.avsi, line 1161)
> (AviSynth_Plugins/QTGMC+.avsi, line 956)

**Comment by Dogway** [comment]
Try updating a few things to see if it still causes errors:
[AVS+ 3.7.3 test 3](https://forum.doom9.org/showthread.php?t=181351)
[NNEDI3CL-1.0.6](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL)
[QTGMC+ 3.94](https://github.com/Dogway/Avisynth-Scripts/blob/master/MIX%20mods/QTGMC+.avsi)

**Comment by ChristianWaechter** [comment]
Thank you, that worked for me. After updating to the QTGMC+ 3.94 script, at first the error message war correct. It told me to update to the latest AviSynth version (my fault) instead of the missing argument "dh". After updating all other files and fixing some dependencies, it is running now.

Just one small off-topic-like question. Is there an actual improvement in image quality when comparing QTGMC+ 3.94 to the latest QTGMC version (without +), or are this "only" speed improvements?

**Comment by Dogway** [comment]
There might be more correct handling since video range is taken into account as well as frame properties overall and HBD support. Also uses NNEDI3CL which is a bit different than nnedi3, as far I could see it resolves corners a bit better. And at last many expressions have been merged so they operate in a 32-bit pipeline and not 8-bit between calls.

**Comment by ChristianWaechter** [comment]
Perfect, so QTGMC+ is the way to go for the absolut last bit of quality. Thank you very much for the explanation and the great work 👍

**Comment by radpopl** [comment]
I received the same message as in the title. I added the NNEDI3CL_rpow2.avsi file from the link above and now I get:
[code][avisynth @ 000002661b5901c0] Script error: There is no function named 'nnedi3wrap'.
(C:/Program Files (x86)/AviSynth+/plugins64+/QTGMC+.avsi, line 1171)
(C:/Program Files (x86)/AviSynth+/plugins64+/QTGMC+.avsi, line 965)[/code]

**Comment by radpopl** [comment]
I received the same message as in the title. I added the NNEDI3CL_rpow2.avsi file from the link above and I still have:

[avisynth @ 000001cee39b01c0] Script error: nnedi3wrap does not have a named argument "dh"
(C:/Program Files (x86)/AviSynth+/plugins64+/QTGMC+.avsi, line 1171)
(C:/Program Files (x86)/AviSynth+/plugins64+/QTGMC+.avsi, line 965)

I downloaded QTGMC+ today, I also have a new test version of AVS+.
