### ISSUE TITLE
In function use GrainFactory3 but in usage still keep use GrainFactory3mod

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#7]
https://github.com/Dogway/Avisynth-Scripts/blob/5946372eafd9d2a3d297807f70ba93d450b1443e/Mods/GrainFactory3mod.avsi#L52

and if function is GrainFactory3, i think you need change name of file GrainFactory3mod.avsi to GrainFactory3.avsi to same name with function

**Comment by Dogway** [comment]
Indeed it's based on mod version by Taro_06, commited.
