### ISSUE TITLE
Typo in QTGMC+.avsi 

### ISSUE THREAD

**Issue by ChristianWaechter** [Dogway/Avisynth-Scripts#73]
**Describe the bug**
I was updating to the latest files of your repository because I wanted to try out the BM3D denoiser. But with my usual call for QTGMCp(), I got an error complaining about a a invalid preset

Avisynth open failure:
ex_BM3D: Wrong 'preset' mode
(AviSynth_Plugins/SMDegrain.avsi, line 1129)
(AviSynth_Plugins/QTGMC+.avsi, line 557)

**Files**
This was a typo in the QTGMC+.avsi file in line 555. It should be `Normal` but is `Normsl`

`(Denoiser == "BM3D")        ? noiseWindow.ex_BM3D(sigma=Sigma,radius=NoiseTR,preset="Normsl",UV=3   ,gpuid=gpuid )`

**Comment by Dogway** [comment]
Thanky!

**Comment by ChristianWaechter** [comment]
I'm not sure either. Presets might be more usefull as a meaningfull naming of the preset might help to choose a suitable preset wich than includes a sigma-value. At least it would be obvious that one would use a `very noisy` preset on a noisy source. But is it not so obviouse which sigma-value to start.

By the way, is there a explanation what the different presets are doing?

**Comment by Dogway** [comment]
'Presets' is mainly an accuracy selector, you can see the table [here](https://github.com/Dogway/Avisynth-Scripts/blob/a8ac9103c7be2ccb8ba32382f4cfa8ad80f0144a/MIX%20mods/QTGMC%2B.avsi#L230).
The problem when associating it noise levels is that for example I oftenly want to deinterlace but not denoise or not at least with QTGMC+, so for noise levels you have extra options like SourceMatch, EZDenoise, EZKeepGrain, and obviously thSAD1 and 2.

I ran a test and default sigma for BM3D seemed acceptable. Closing for now.
