### ISSUE TITLE
FillBorders

### ISSUE THREAD

**Issue by Asd-g** [Dogway/Avisynth-Scripts#75]
**Describe the bug**
Hi,
I saw you have some FillBorders calls. If FillBorders 1.4.0 is used, there could be error.

**To Reproduce**
```
Colorbars(pixel_type="yv12")
PadBorders(4, 4, 4, 4, mode="fill")
```
For example, in [PadBorders](https://github.com/Dogway/Avisynth-Scripts/blob/master/ResizersPack.avsi#L1229-L1230) you probably want to use `FillBorders(left=l,top=t,right=r,bottom=b,mode=6)`.

I didn't check the usage of FillBorders in `Stabilization Tools Pack.avsi` but if the values aren't used with named parameters, there will be error too.

**Comment by Dogway** [comment]
Thanks, didn't know they were mandatory now. Updated.
"Stabilization Tools Pack" is legacy and unmaintained, it uses a function called FillBorder(s) (had to remove the 's') I made way back but I keep the script for reference now only now because this area hasn't been explored too much.
