### ISSUE TITLE
Worse SMDegrain comparing version v3.1.2d and v4.4.0d

### ISSUE THREAD

**Issue by Valdiralita** [Dogway/Avisynth-Scripts#78]
**Describe the bug**
Comparing the output from the older (v3.1.2d) to the newer version (v4.4.0d) there is reduced denoising producing larger files.
Increasing thSAD produces blurrier AND larger files.

**To Reproduce**
Denoise a sample file with this script and compare the file sizes. In my tests the newer version creates files around double in size:
`SMDegrain(tr=2, thSAD=300, contrasharp=true, refinemotion=true) `

When testing other values i found that encoding with the old version, with the script above, and the new version with this script:
`SMDegrain(tr=6, thSAD=600, contrasharp=true, refinemotion=true) `
the newer version will produce bigger files and blurrier images.

**Expected behavior**
The denoising should produce roughly the same denoise strength and filesize for equal settings or it should be possible to tune it to get a similar result.

**Files**
DM me on discord or doom9 for my sample files if needed.

**System:**
 - OS: Windows 10
 - Old Version: SMDegrain v3.1.2d, StaxRip v2.12, AviSynth+ 3.7.3 r3661 x64
 - New Version: SMDegrain v4.4.0d, StaxRip v2.25, AviSynth+ 3.7.3 r4003 x64

**Comment by Dogway** [comment]
The newer SMDegrain (currently v4.5.0) is tailored for better detail preservation. Depending on the source we are talking about you might be denoising more with the old version or losing more details in the form of smearing/motion blur.

The structure of the filter is still the same but some defaults have been changed via Zopti optimization for this goal. So for light denoise you shouldn't see increased blurriness but better detail preservation specially on dark areas, low contrast areas and in motion areas, and for medium to high grain the filter is designed to rely on prefilters as thSAD won't simply cut it to discern what is grain and what not.

Here is a list of prefilters, by using these you can lower thSAD. Read the part that starts _"In general terms..."_ to apply different filters depending on strength and source type (live action or anime).

https://raw.githack.com/Dogway/Avisynth-Scripts/master/SMDegrain/SMDegrain.html#prefilter2

**Comment by Dogway** [comment]
Did it help? If not I'd need a source sample, but better move the discussion to Doom9 then.
