### ISSUE TITLE
FlatMask HBD

### ISSUE THREAD

**Issue by realfinder** [Dogway/Avisynth-Scripts#8]
I did delete the edited MasksPack but I note you didn't added HBD in FlatMask, here the deleted file with HBD mod I did
https://github.com/realfinder/AVS-Stuff/blob/0424f48522f67a021ecb4f8b72802c45a1c3c693/avs%202.5%20and%20up/MasksPack.avsi#L190

**Comment by Dogway** [comment]
FlatMask needs also a rehaul, probably a port of mt_hysteresis to ExTools as well, so there's much work expected. I will complete phase 1 with your update and then think of a rehaul.

**Comment by Dogway** [comment]
Done: https://github.com/Dogway/Avisynth-Scripts/commit/3ee9513f4bc3a5b9be71019b6a7cbfd0e08d570a
