### ISSUE TITLE
DGDenoise new syntax

### ISSUE THREAD

**Issue by tormento** [Dogway/Avisynth-Scripts#84]
DGDenoise has a new syntax and the author is testing temporal denoising.

Please, when you'll have time, fix your scripts accordingly or add a mode=9 :)

**Comment by Dogway** [comment]
Thanks I will check

**Comment by tormento** [comment]
DG has released test 4, packing some CUDA functions directly in DGSource call, all working without leaving GPU card.

It's way faster than anything that I have seen with good quality too. Separate DGDenoise is coming in a few hours (days?).

When I wrote the first message, I thought it would be a faster release for the separate function but some issues arose (including my ban from his board 😂).

Anyway you can find the new test4 [here](https://rationalqm.us/misc/DGDecodeNV_test4.zip).

The very interesting part, beside temporal denoising, is the feature where you can directly see what parts are denoised. You could use that as mask.

**Comment by Dogway** [comment]
> @Dogway standalone DGDenoise with the new syntax has been [released](https://rationalqm.us/misc/DGDecodeNV_test5.zip), if you want to try to implement it.

Thank you, I'll have a look this weekend if time permits
