### ISSUE TITLE
FilmGrainPlus, presets "5245" and "5274" fail

### ISSUE THREAD

**Issue by Boulder08** [Dogway/Avisynth-Scripts#86]
Tried different bitdepths, but the same issue occurs when opening the script.

![image](https://github.com/Dogway/Avisynth-Scripts/assets/11799308/aba7145b-026b-4165-bdb7-e02b2d42ac7d)

**Comment by Dogway** [comment]
Works for me in 8 and 16-bit tested. Would you mind sharing your call?

**Comment by Boulder08** [comment]
Fortunately it is a very simple script:
`BlankClip(width=1920, height=1080, length=100, pixel_type="YV12", color=$656565).killaudio()
FilmGrainPlus(fast=false,preset="5245").ConvertBits(10)`

16-bit BlankClip gives me the same error as well.

**Comment by Dogway** [comment]
Updated the script, try now with a02ab72341b3597b4aeaacb8d7f3bcb33a68849e

**Comment by Boulder08** [comment]
Works now :)
